services:
  mysql-sftps:
    container_name: mysql-sftps
    image: docker.io/bitnami/mysql:9.4.0
    restart: 'always'
    ports:
      - '127.0.0.1:33063:3306'
    volumes:
      - 'mysql-sftps:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=sftps
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123123a
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql-sftps:
    name: mysql-sftps
    driver: local