CREATE TABLE tbl_cluster_SPRING_SESSION
(
    PRIMARY_ID            VARCHAR(36) NOT NULL,
    SESSION_ID            VARCHAR(36) NOT NULL,
    CREATION_TIME         BIGINT      NOT NULL,
    LAST_ACCESS_TIME      BIGINT      NOT NULL,
    MAX_INACTIVE_INTERVAL INT         NOT NULL,
    EXPIRY_TIME           BIGINT      NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    INDEX (EXPIRY_TIME),
    INDEX (PRINCIPAL_NAME),
    UNIQUE (SESSION_ID),
    PRIMARY KEY (PRIMARY_ID)
) ENGINE = InnoDB
  ROW_FORMAT = DYNAMIC;

CREATE TABLE tbl_cluster_SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID VARCHAR(36)  NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    LONGBLOB     NOT NULL,
    FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES tbl_cluster_SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
) ENGINE = InnoDB
  ROW_FORMAT = DYNAMIC;
